name: Run cppcheck-action
on:
  workflow_dispatch:  
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    
jobs:
  cppcheck-annotations_scr:
    name: cppcheck-annotations /src
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run cppcheck-annotation-action
        uses: Konstantin343/cppcheck-annotation-action@v1.0
        with:
          std: 'c99'
          platform: 'unix64'
          log-level: 'verbose'
          sources: './src'
          annotation-failures: 'warning'
          # suppress: 'unusedFunction'
          # annotation-level-default: 'error'

      - name: Annotate lines with errors src
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'Results of CppCheck src files'
          input: 'annotations.json'
  cppcheck-annotations_test_scr:
    name: cppcheck-annotations /test/lcd_hd44780
    runs-on: ubuntu-latest
    steps:
      - name: Run cppcheck-annotation-action
        uses: Konstantin343/cppcheck-annotation-action@v1.0
        with:
          std: 'c99'
          platform: 'unix64'
          log-level: 'verbose'
          sources: './test/lcd_hd44780'
          annotation-failures: 'warning'
          # suppress: 'unusedFunction'
          # annotation-level-default: 'error'

      - name: Annotate lines with errors test_src
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'Results of CppCheck test src files'
          input: 'annotations.json'