name: Run Template Unit Tests
on:
  workflow_dispatch:
  # push:
  #   branches: [main, develop]
  # pull_request:
  #   branches: [main, develop]
jobs:
  template_test_running:
    name: Template Test RUN
    runs-on: windows-latest 
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with:
        submodules: recursive
        
    - name: arm-none-eabi-gcc
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10-2021.10'
        
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
        
    - name: Build binary
      working-directory: test/template
      run: |
        mkdir out
        cmake -Bout -GNinja
        cmake --build out

    - name: List files
      working-directory: test/template/out
      run: dir

    - name: Run template tests
      working-directory: test/template/out
      run: ./template_test.exe -v

  # template_2_test_running:
  #   name: template_2 Test RUN
  #   runs-on: windows-latest 
  #   # strategy:
  #   #   matrix:
  #   #     os: [ubuntu-latest, windows-latest]
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4.0.0
  #     with:
  #       submodules: recursive
        
  #   - name: arm-none-eabi-gcc
  #     uses: ryanwinter/arm-none-eabi-gcc@master
  #     with:
  #       release: '10-2021.10'
        
  #   - name: Install Ninja
  #     uses: seanmiddleditch/gha-setup-ninja@v3
        
  #   - name: Build binary
  #     working-directory: test/template_2
  #     run: |
  #       mkdir out
  #       cmake -Bout -GNinja
  #       cmake --build out

  #   - name: List files
  #     working-directory: test/template_2/out
  #     run: dir

  #   - name: Run inputs tests
  #     working-directory: test/template_2/out
  #     run: ./template_2_test.exe -v
