name: Run Lizard Library Check
on: 
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  lizard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Lizard Runner
        uses: Uno-Takashi/Lizard-Runner@v3
        with:
          path: "./src"
          CCN: "12"
          Threshold: "nloc=30"
          language: "cpp"
          verbose: "true"
          arguments: "4"

        
