name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check_library: "disable"
          skip_preprocessor: "disable"
          enable: "all"
          exclude_check: "./test"
          inconclusive: "disable"
          inline_suppression: "disable"
          force_language: "c,c++"
          force: "enable"
          max_ctu_depth: "2"
          platform: "unspecified"
          std: "c99"
          output_file: ./reports/cppcheck_report.txt
          other_options: "disable"

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'feature/add_gihubactions_cppcheck' # your branch name goes here
          