name: Run cppcheck-action
on:
  workflow_dispatch:  
  push:
    branches: [main, develop, feature/add_gihubactions_cppcheck]
  pull_request:
    branches: [main, develop]
    
jobs:
  build:
    name: cppcheck-annotations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run cppcheck-annotation-action
        uses: Konstantin343/cppcheck-annotation-action@v1.0
        with:
          std: 'c++14'
          platform: 'unix64'
          log-level: 'verbose'
          sources: "./src"

      - name: Annotate lines with errors
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'Results of CppCheck'
          input: 'annotations.json'