name: Run LCD HD44780 Unit Tests
on:
  workflow_dispatch: 
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  LCD_HD44780_test_running_win:
    name: LCD HD44780 Unit Test RUN on Win
    runs-on: windows-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.0.0
      with:
        submodules: recursive
        
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
        
    - name: Build binary
      working-directory: test/lcd_hd44780
      run: |
        mkdir out
        cmake -Bout -GNinja
        cmake --build out

    - name: Run LCD HD44780 tests
      working-directory: test/lcd_hd44780/out
      run: ./lcd_hd44780_test.exe -v

  LCD_HD44780_AVR_test_running_win:
    name: LCD HD44780 for AVR Unit Test RUN on Win
    runs-on: windows-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.0.0
      with:
        submodules: recursive
        
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
        
    - name: Build binary
      working-directory: test/lcd_hd44780
      run: |
        mkdir out_avr
        cmake -S ./avr_code_test -B out_avr -GNinja
        cmake --build out_avr

    - name: Run LCD HD44780 tests
      working-directory: test/lcd_hd44780/out_avr
      run: ./lcd_hd44780_test.exe -v

  LCD_HD44780_test_running_ubuntu:
    name:  RUN LCD HD44780 Unit Test on Ubuntu
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.0.0
      with:
        submodules: recursive
        
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
        
    - name: Build binary
      working-directory: test/lcd_hd44780
      run: |
        mkdir out
        cmake -Bout -GNinja
        cmake --build out

    - name: Run LCD HD44780 tests
      working-directory: test/lcd_hd44780/out
      run: ./lcd_hd44780_test -v      




  # template_2_test_running:
  #   name: template_2 Test RUN
  #   runs-on: windows-latest 
  #   # strategy:
  #   #   matrix:
  #   #     os: [ubuntu-latest, windows-latest]
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4.0.0
  #     with:
  #       submodules: recursive
        
  #   - name: Install Ninja
  #     uses: seanmiddleditch/gha-setup-ninja@v3
        
  #   - name: Build binary
  #     working-directory: test/template_2
  #     run: |
  #       mkdir out
  #       cmake -Bout -GNinja
  #       cmake --build out

  #   - name: List files
  #     working-directory: test/template_2/out
  #     run: dir

  #   - name: Run inputs tests
  #     working-directory: test/template_2/out
  #     run: ./template_2_test.exe -v
