name: self-hosted test
on:
  workflow_dispatch:
  # push:
  #   branches: [main, develop]
  # pull_request:
  #   branches: [main, develop]
jobs: 
  formatting_check_docker_runner:
    name: Gcc_test
    runs-on: test-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    
    - name: test
      run: arm-none-eabi-gcc --version

    - name: programmer check
      run: STM32_Programmer_CLI -l

    - name: Build binary
      working-directory: test/inputs
      run: |
        mkdir out
        cmake -Bout -GNinja
        cmake --build out
